import { Link } from "react-router-dom";

const Help = () => {
  return (

     <div className=" rounded-3xl bg-[#00b4d8] font-serif text-2xl">

               <p className="p-5 font-light">Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta corrupti totam, aut alias, repudiandae sequi facilis perspiciatis sunt tempore mollitia officiis. Neque, mollitia odio minus nostrum rem inventore optio minima?
               Odio nemo, dolores sed dolor error dicta necessitatibus! Odio tempora voluptatem vitae fugiat, aperiam eveniet, sint nisi, molestias dolorum unde doloribus eaque earum explicabo ex! Rerum dolorem odio id aperiam!
               Quod, officia. Quisquam temporibus reiciendis iste expedita blanditiis minima natus ratione odit a doloremque nam vero id necessitatibus repudiandae, maxime soluta neque aspernatur, officiis accusantium laudantium omnis! Laborum, praesentium ipsam.
               Error amet aliquid accusamus eos natus in temporibus, cum adipisci numquam rerum, ullam maiores impedit quae necessitatibus! Dicta reprehenderit minus quam doloribus, provident id harum modi, animi eius, similique hic!
               Ipsa harum sapiente non ab fugit nulla aut aspernatur minus natus numquam debitis eaque, qui dolor autem mollitia cumque est officiis eveniet quasi modi fuga. Sunt, ab. Suscipit, a natus.
               Nesciunt quas deserunt earum, corrupti eveniet at quae odio pariatur harum sequi accusamus, facilis aut soluta ut porro saepe corporis repellat? Reiciendis voluptatibus unde nemo sequi aspernatur sunt est non?
               Voluptate explicabo eos tempora veniam magni, vel perspiciatis libero molestiae, qui asperiores pariatur iste, excepturi doloribus consequatur quibusdam. Culpa at accusamus odit quae molestias. Animi suscipit a consectetur maiores in.
               Dolores voluptatibus voluptates quae sequi eos incidunt laudantium, ut mollitia aut aperiam provident unde perferendis iusto ducimus deleniti placeat temporibus ullam qui. Eaque, asperiores. Necessitatibus saepe temporibus corrupti nihil quod.
               Natus, eligendi? Laboriosam, aut alias quo nesciunt sapiente animi odit perspiciatis soluta, corrupti eaque, necessitatibus quos. Asperiores vero repellat nostrum nemo, quasi officia minus pariatur magnam optio alias atque corrupti.
               Libero minus nesciunt dolor culpa, laudantium porro tempora asperiores. Veniam, blanditiis iste odio, quia quae rem voluptatem, ab velit maxime vero laborum magnam? Totam voluptatibus, officiis omnis esse distinctio vitae.
               Asperiores esse rerum perferendis repellat ducimus voluptates illo nam. Dignissimos, laborum! Est repellat asperiores libero quos ipsam, ab illo, alias quaerat quam sequi blanditiis, nisi accusamus harum necessitatibus sapiente. Corrupti!
               Vel quo corrupti est, odio sed omnis officia a pariatur saepe beatae at distinctio, iure rem amet expedita aliquid. Est accusantium perspiciatis nisi molestiae necessitatibus fuga magnam? Minus, sed sapiente.
               Beatae officia odio ipsam itaque unde excepturi vitae dolores nihil atque sint, ullam quia expedita laborum accusamus nobis, ipsa dolor officiis non necessitatibus asperiores exercitationem dolorum adipisci distinctio? Incidunt, sit!
               Veniam, numquam? Eos molestiae eligendi nostrum dolores sequi nulla sint rem ex praesentium odio deserunt ipsum cumque veritatis, tempore rerum. Doloremque eius dicta accusantium tempora amet esse quia quis ab.
               Quidem, facilis iure assumenda iusto atque in fugiat perferendis, iste illo ea voluptatum. Sed reiciendis ea est, inventore veritatis corporis, eos hic at aspernatur ipsam animi quis tenetur officiis cum!
               Facilis voluptas laudantium atque voluptatibus eligendi id incidunt unde molestiae perferendis ipsam a voluptatem accusantium esse fuga, beatae saepe earum dolores adipisci libero ab debitis ex repudiandae vel? Praesentium, sit?
               Cupiditate reprehenderit quibusdam fugit quam repellendus quis error accusantium veritatis possimus, officia perspiciatis, aliquam nesciunt sequi rerum eaque temporibus facilis. Vero eveniet aperiam velit quis nulla doloribus voluptate temporibus sed.
               Architecto nihil molestiae perspiciatis magni modi qui, neque, reiciendis nulla ipsam quia recusandae quo facere deserunt similique amet, pariatur beatae. Distinctio ipsa consequuntur obcaecati illo unde molestias numquam cum et.
               Quod similique rem et doloribus voluptatum, quis sit assumenda at dolore reprehenderit odit expedita magni consectetur deserunt ipsam! Itaque sequi quas iure officia perspiciatis praesentium excepturi est sapiente incidunt dolore.
               Nulla, numquam consequatur cupiditate omnis porro error voluptate! Sint repellendus eaque placeat amet! Dolores in, et dolore fugiat perferendis vitae dolorem, aliquid maxime, deleniti itaque adipisci voluptatum porro at cumque!
               Provident praesentium excepturi, accusantium id modi doloribus. Sapiente numquam, dolorem distinctio voluptates vitae sit. Pariatur illo dicta suscipit quas ut dolores officiis consectetur quasi quis, officia accusantium doloremque placeat aliquid?
               Debitis saepe tempore hic culpa aut suscipit repellendus consequuntur vero nemo facere? Iusto sapiente iste, consequuntur rerum possimus saepe vel repudiandae ad esse minus expedita, ea porro. Ipsa, eaque in.
               Iure excepturi nisi asperiores ex maxime ullam autem inventore at! Corporis eos quia iste recusandae unde doloribus, alias molestiae voluptatem voluptatibus, nisi similique placeat non repellendus saepe voluptate vero harum?
               Debitis ipsum ducimus magnam unde maiores alias deserunt tempora, voluptas laudantium quasi odio magni expedita repudiandae quibusdam, velit itaque corporis! Tenetur necessitatibus consequatur facere cum vitae placeat dolorem officia iste.
               Repudiandae ea laboriosam soluta dolore, rerum ratione, culpa recusandae in nihil ut sed similique delectus placeat natus nesciunt aspernatur deserunt odit, possimus quos magnam nobis! Libero sint soluta nemo voluptatum!
               Velit labore fugit quis vitae repellat id, ipsam doloribus facilis unde neque earum sequi corrupti sed non nostrum dolorum rerum libero suscipit ab numquam amet, reprehenderit architecto. Aut, unde assumenda.
               Itaque ratione sequi quas labore ullam placeat tempore impedit tenetur, facere consequuntur quam illo corporis libero excepturi consequatur vel similique, debitis, laborum fugit voluptatibus eum reprehenderit vero commodi quia. Est!
               Facilis obcaecati nulla, iure repellendus quia eveniet minima quisquam aliquam odit assumenda dolores error inventore iusto blanditiis maxime tempora et quis quod consectetur hic deserunt? Beatae blanditiis nostrum nesciunt similique.
               Excepturi, ipsum! Voluptas incidunt, velit minima dolorum numquam aperiam sequi laudantium, sit ex nemo nihil iusto, ullam voluptate praesentium. Eius voluptatum odit quae rerum, soluta eaque labore. Aspernatur, nobis cupiditate!
               Quae sapiente saepe porro modi quisquam quibusdam perferendis et ipsam, facilis molestiae, autem ullam, maxime officia rem unde delectus laudantium dolorum fugit minus vitae sit accusantium reprehenderit magnam maiores? Voluptatem!
               Maxime, rem vel. Velit cumque laudantium error sed quasi sint est aliquid deserunt. Impedit incidunt nesciunt, animi maiores vero sit id ipsam voluptatibus, mollitia nobis in quo ducimus esse repellat?
               Illo ratione neque deserunt molestiae assumenda placeat laudantium facilis, odio laboriosam eos incidunt perspiciatis doloremque dolorum accusantium consequuntur deleniti reprehenderit? Ex debitis mollitia provident eveniet quo nesciunt, deserunt et quisquam.
               Quas, beatae itaque placeat officia nihil laboriosam pariatur natus fuga quibusdam ipsam nisi voluptates cum adipisci aliquid quasi libero, animi repellendus exercitationem id saepe? Perspiciatis inventore adipisci quod dicta iusto.
               Perferendis expedita est maxime. Unde animi mollitia impedit? Perspiciatis error iure incidunt est et delectus blanditiis placeat illum minima vitae quisquam qui, ratione exercitationem sed non odio quos aliquam minus?
               Tempora iusto voluptas id ratione mollitia repudiandae molestiae sunt suscipit reiciendis reprehenderit tempore sed facere nostrum, pariatur nulla. Sapiente recusandae, rerum consequatur fuga excepturi facere tenetur magnam assumenda. Fugiat, quaerat?
               Incidunt eaque officiis accusantium, quo fugit libero voluptate nemo ex repudiandae maxime, id iure vel magnam cumque et! Delectus culpa reprehenderit doloribus consequuntur quaerat dolores numquam, eligendi eos ratione aliquam.
               Provident atque ex deserunt facere asperiores iusto, error cumque vel non placeat ducimus totam magni pariatur in debitis et corrupti, porro ratione id ab sit qui explicabo. Repellat, iusto eveniet!
               Necessitatibus enim inventore vero. Laudantium corporis tenetur ullam beatae, consequuntur voluptatem deleniti officiis eos dolorum qui facere nostrum, quas atque, nemo sed aperiam minima illum. Iure quaerat natus nam quas!
               Assumenda inventore deserunt exercitationem! Reiciendis aspernatur consectetur nostrum blanditiis totam natus tempora autem placeat asperiores vero doloremque sapiente laudantium, numquam consequuntur possimus incidunt quidem distinctio dignissimos nemo corporis deserunt facere!
               Amet culpa cupiditate expedita reiciendis obcaecati aliquam possimus at ducimus blanditiis labore incidunt corporis explicabo consequatur assumenda quia nostrum neque repellendus nesciunt maiores, porro optio ipsum dolorem eum! Voluptate, quam?
               Laboriosam fugit quibusdam quasi maxime eveniet voluptatum in hic architecto repellat necessitatibus dolore, labore eum distinctio sunt tempora mollitia reiciendis quis voluptas similique veritatis impedit porro ipsum? Culpa, omnis accusantium!
               Itaque quasi, laborum quidem fuga, odit modi temporibus incidunt voluptate tenetur perferendis id inventore minima voluptatum eveniet. Error, accusantium veritatis asperiores, nemo incidunt corporis repellendus, quia sint architecto itaque perspiciatis?
               Itaque excepturi fuga explicabo quod vel repudiandae nesciunt quibusdam placeat debitis, veritatis doloribus eveniet, delectus laudantium doloremque nam ipsam id ipsa quidem libero? Praesentium voluptate eaque saepe? Iusto, deleniti maiores?
               Illo totam magnam odio nesciunt officiis sed hic ducimus veritatis error ut maxime suscipit, ad dolorem dolore optio nobis ab rerum quis! Cum ex, saepe dicta numquam accusantium dignissimos magnam!
               Iusto reiciendis beatae repudiandae ipsum quia facilis at laudantium earum. Nostrum perferendis deleniti praesentium commodi ut totam, cupiditate nam odit delectus veniam provident inventore asperiores nesciunt sed accusamus. Unde, voluptate.
               Iure ad, illum, nisi laborum dolorum fugit veritatis quod earum modi non ab dolorem porro? Quidem voluptatem provident amet laboriosam consequatur a alias corporis veniam voluptate harum. Alias, officiis molestiae.
               Explicabo, iste. Dolorem adipisci tempore facilis magni et, debitis dolore, minima sed laborum repellendus sit assumenda dicta accusamus iste. Explicabo eos rem enim perspiciatis quidem? Rerum hic optio ab odit!
               Aspernatur porro excepturi reprehenderit, exercitationem quod obcaecati, tempora saepe non recusandae officiis facere, nobis adipisci. Tempora mollitia sint maiores ducimus, accusamus consectetur, optio soluta distinctio cumque voluptatibus, veritatis provident non.
               Quisquam, quos neque officiis tempora pariatur explicabo cum atque, alias rem ab deleniti vero aspernatur dicta recusandae nihil sed consequuntur eos! Natus obcaecati est, rerum cum recusandae blanditiis qui quas.
               Libero laborum tempore repudiandae, similique nostrum adipisci quaerat mollitia doloremque maxime quos minus delectus vero tempora perspiciatis, est earum eos fugit a error quis modi reprehenderit explicabo? Laudantium, consectetur expedita!
               Quisquam voluptate quaerat, molestiae quis dolores, libero soluta vel nisi officiis accusantium molestias porro consectetur aut veniam, laborum nulla adipisci maiores deserunt. Ducimus, ullam eum distinctio cumque cum voluptatibus rem.
               Aperiam veniam veritatis eligendi quae nesciunt molestiae ducimus recusandae harum? Labore adipisci reiciendis doloribus! Dolorem nam, vitae, consequuntur quas veritatis praesentium doloremque reiciendis veniam ab saepe molestiae sit blanditiis voluptatibus.
               Temporibus, eos tenetur vitae incidunt iusto vel quisquam nihil, maiores error totam repellendus nisi minima voluptatibus id similique hic ex perferendis odio vero soluta! Libero incidunt adipisci tenetur eum quia.
               Obcaecati quibusdam accusamus fuga amet laudantium nisi sed cupiditate deserunt soluta omnis ea sequi maiores unde, inventore animi pariatur ratione id temporibus nulla corrupti quod harum atque. Ex, quis laborum.
               Similique nulla voluptate blanditiis tenetur corporis illum nihil fugiat a obcaecati hic velit odit dicta maxime, voluptates omnis. Quisquam sunt accusamus cum. Enim vitae voluptates error nobis qui amet sint.
               Distinctio natus, fugit nam quo ipsa obcaecati totam? Nemo nulla, nam unde repellat explicabo, sit illum eum deserunt velit labore quae accusamus eos nihil at, inventore amet ad expedita praesentium!
               Id quo, neque, exercitationem recusandae error expedita omnis tempora quasi minus velit repellendus! Voluptates qui placeat aut recusandae quas earum quia, nam rerum cupiditate velit inventore, eum neque? Cupiditate, quas?
               Possimus ipsam sequi beatae tempore pariatur non et? Nam quo corrupti qui itaque beatae corporis vitae magni, sit officia a minus similique vero quibusdam alias quidem quos tenetur! Vel, atque.
               Nemo voluptatem molestias maxime, accusantium hic temporibus natus voluptatum pariatur nesciunt dolore? Facere rerum suscipit dicta laudantium pariatur aspernatur odit sint exercitationem quisquam, illo dolorum quas accusamus corrupti aliquam iusto.
               Porro non dicta ipsam rerum ad quos nam reprehenderit architecto provident maxime, voluptatibus deserunt quisquam numquam ex esse ut autem. Omnis sint nulla ut et, incidunt pariatur magnam. Tempora, autem.
               Voluptates amet ipsum quam voluptatem saepe vel numquam ullam possimus esse commodi soluta, itaque vitae error voluptas mollitia fuga, quibusdam molestias sapiente harum, aliquid quia! Labore consequatur quasi laudantium minus?
               Tenetur ut placeat reprehenderit ad tempore ex corrupti pariatur magnam sequi sit voluptate quo eligendi exercitationem animi repudiandae molestias atque praesentium numquam molestiae, odio facere iste deleniti. Molestias, sequi ullam.
               Porro nihil earum quia cum consequatur adipisci, exercitationem quod cumque temporibus quibusdam, eius eaque aspernatur quo? Odio possimus distinctio, nostrum nulla quam, modi numquam fuga, aut accusamus labore ut inventore.
               Aspernatur libero voluptatibus inventore ut architecto quisquam rem hic nisi minima nihil modi iusto facere porro dolorem expedita eaque dolores nostrum odit, aliquam perspiciatis laboriosam velit tempora. Corrupti, quod placeat.
               Labore laborum odio repellendus fugit. Dolores laudantium dolore exercitationem eos distinctio accusamus, voluptatibus fugiat eveniet commodi labore tempore nemo unde soluta, aliquam aspernatur consequuntur, excepturi veritatis. In suscipit ducimus nobis!
               Repellendus laboriosam ullam voluptatibus modi doloribus! Qui, tempora aut impedit quis iure incidunt in quibusdam obcaecati placeat sunt sed magnam aliquam? Architecto aperiam, earum possimus culpa a numquam nihil aspernatur?
               Deleniti quo et ipsum ab assumenda? Odio eveniet iure unde doloremque iusto hic omnis eum? Modi enim inventore est optio, animi iure, repellat adipisci illum, labore ea vero voluptatem. Cupiditate?
               Explicabo, aperiam ipsum, nulla praesentium aspernatur commodi ab provident distinctio fugiat similique rem ipsa fugit eaque beatae odio corporis? Dolorum neque saepe officiis asperiores adipisci quia, pariatur sed facilis placeat!
               Omnis reprehenderit voluptatibus similique provident voluptate modi temporibus adipisci vitae perspiciatis amet, repellat fuga laudantium obcaecati, veniam molestiae sequi expedita nostrum porro quidem dignissimos quam fugiat laboriosam enim. Debitis, nobis.
               Optio est mollitia maxime eos nostrum iusto assumenda laboriosam cupiditate non odit fugiat officiis, alias corporis at esse reprehenderit totam consequuntur earum error cumque! Consequuntur corporis repellendus dolore inventore similique.
               Velit repellat atque debitis iste nam, excepturi asperiores error! Esse veritatis neque asperiores, sapiente modi fugit cumque, itaque doloribus libero corporis, necessitatibus in? Fuga eligendi commodi, velit consequatur doloremque iusto!
               Sed error ullam exercitationem fugit nihil natus iusto non, eligendi dignissimos laborum aperiam ipsa odit autem maiores dolorum voluptatem tempora molestiae nam! Fugiat neque qui numquam rem veritatis? Illum, ab.
               Illum et ab reiciendis eum, quasi facilis id sed ex odit eius blanditiis? Quisquam laboriosam perspiciatis veniam, expedita doloribus possimus eos ducimus fugiat neque reprehenderit ab, quis nostrum quo officiis!
               Beatae veritatis magnam aperiam maiores qui nulla, illum ipsa vitae saepe autem velit totam perspiciatis harum error quos. Molestiae, amet aut reprehenderit sequi libero illum unde consequatur. Consequuntur, similique possimus.
               Nesciunt beatae veniam aut illum possimus fugiat suscipit illo in sunt dolore animi ducimus laudantium corporis exercitationem alias ipsam, numquam maiores provident voluptate. Nam, praesentium suscipit debitis dolores incidunt quas.
               Ex officiis quaerat distinctio ipsa nemo cumque molestiae, libero delectus accusamus laboriosam provident tempora natus enim. Sint veniam delectus, beatae vitae pariatur amet aliquam, dignissimos assumenda, doloribus cupiditate debitis blanditiis!
               Ex fuga incidunt illum inventore tempore est sed labore repudiandae, recusandae commodi aperiam consectetur ipsum quae dolor, corporis sint aut? Provident consectetur ad exercitationem corrupti quos eius architecto modi cum!
               Sint non architecto velit ipsum. Saepe itaque qui, eligendi deserunt nostrum sint debitis voluptate provident at recusandae necessitatibus sed error corrupti, officia a ab! Facilis expedita dolores dolorem aliquid ipsam?
               Optio dolore quod cumque, libero magnam eos totam. Dicta iste iusto similique dolor impedit rerum, atque eaque a recusandae dolore amet obcaecati, quae consectetur. Dolor exercitationem dicta reiciendis quaerat quos.
               Culpa recusandae dolore eligendi, quos sit veniam dolorem molestias totam illum accusantium eos porro temporibus voluptate cumque vitae non necessitatibus. Perspiciatis deserunt, aliquid aspernatur voluptatem ipsa nulla maiores animi doloremque.
               Molestiae a, ipsum ullam aut tenetur quis exercitationem laudantium quo cupiditate voluptatum, aspernatur at blanditiis quibusdam, iure error deleniti. Reiciendis eos cumque magni provident exercitationem voluptates possimus dignissimos, veniam quae?
               Quas reprehenderit aliquam natus accusantium nemo optio explicabo molestias ducimus repellendus adipisci et facilis expedita quis nihil, nulla aperiam tempora fugit atque sint doloremque at excepturi officiis dolores! Totam, doloribus.
               Blanditiis nemo maiores veniam omnis, nam vitae laboriosam non odit modi voluptas fugiat. Qui dignissimos deserunt cumque assumenda veniam iusto quo facilis, quisquam nostrum. Cupiditate quasi rem vero unde nobis!
               Ex ipsum ducimus est et, rerum voluptate consectetur quia cum molestiae nihil veniam. Officia nihil soluta, atque accusantium earum, veniam consequuntur itaque mollitia quos incidunt nostrum molestiae, ab iste. Natus?
               Esse recusandae quod repellat, possimus facilis, excepturi ex alias ab aperiam quaerat commodi odit impedit laudantium explicabo, sint maxime laborum officia dignissimos sit libero. Dolores eum omnis accusamus ab ipsa?
               Sed obcaecati facilis odit nisi illum voluptate numquam, libero dicta sint. Veniam quis temporibus distinctio necessitatibus fuga, deserunt quaerat quia ratione sunt quisquam labore non neque, repudiandae modi accusantium deleniti?
               Odio, consequatur ex alias in quia facere eius incidunt omnis assumenda quaerat porro illo quis velit voluptatum sapiente expedita, nisi delectus dolore culpa. Repudiandae, tempore? Quibusdam eius mollitia itaque autem!
               Suscipit cum magni modi voluptatibus repudiandae in eligendi totam maxime quam quidem ab officiis consequatur, nostrum, eveniet expedita quos dolor nam alias aspernatur corrupti debitis magnam? Eligendi laudantium eaque perferendis.
               Ab explicabo aut voluptate non. Ut sunt, minima saepe quis at laudantium delectus distinctio harum neque soluta omnis necessitatibus. Nulla nisi quisquam nobis officia? Laborum esse quae sunt maxime suscipit.
               Dolorem unde, voluptatibus, perspiciatis magnam quo soluta, iste ducimus cupiditate repellendus ea ipsam sapiente! Dolore sit commodi, sapiente sunt, alias exercitationem maxime nobis ab temporibus minus adipisci, quod odio optio?
               Distinctio consequatur quisquam repellendus quae aperiam amet culpa dolor, tempora ea, debitis, suscipit obcaecati ducimus. Ipsa possimus quae minima quo consectetur, maxime dolorum aliquam consequuntur magnam, quam, molestias iste esse?
               Est repellat, animi inventore omnis laudantium qui in similique. Reiciendis rerum excepturi dolores nulla quos voluptatum voluptate? Atque voluptatem quibusdam nulla quae possimus, eius voluptatibus sit doloribus vel accusantium animi.
               Dolores ipsam vel, distinctio beatae repellendus quis, consequuntur aspernatur similique illo optio incidunt, praesentium earum atque ad esse voluptate? Suscipit voluptates deleniti veniam libero reprehenderit quaerat tempore ratione architecto doloremque.
               Delectus repellat aut assumenda omnis minus illo cumque dignissimos non rerum autem velit, officiis, nisi inventore culpa quam molestiae deleniti reiciendis cupiditate ad suscipit molestias dolorum fugiat alias! Dolor, aliquam!
               Blanditiis autem quis eius eos illum architecto explicabo laborum commodi corrupti repellendus, vitae dolorem ullam ipsum vel dolorum, iusto pariatur excepturi in ut non minus odit debitis sit at! Eius?
               Quod quisquam, iusto voluptatem esse accusantium non. Reprehenderit officia pariatur quaerat excepturi a minus error quo laboriosam ea culpa, veritatis quidem nobis voluptatibus commodi minima ab assumenda quos ipsum ut!
               Impedit, neque. Vitae aspernatur doloremque et consequuntur nemo quis, error temporibus modi ratione neque ipsam aperiam nulla laboriosam optio non? Voluptate, voluptatum quisquam sapiente consequatur ad deleniti facere error est.
               Facere iusto natus distinctio labore expedita voluptatibus. Dolore excepturi possimus cum tempora aperiam doloremque amet libero? Tenetur, accusantium et ex voluptate blanditiis expedita eum labore exercitationem possimus, fugit commodi provident.
               Odio beatae, at maiores veritatis assumenda omnis perferendis sunt id. Alias aut eaque exercitationem minus deleniti, explicabo ea dolorum laboriosam? Sequi quasi quis dolore ut adipisci iusto, quae sit nemo?
               Aut et porro quis saepe quibusdam aliquam magni soluta. Velit facere pariatur eius autem iusto temporibus nemo cupiditate assumenda, dolore porro fugiat iste reiciendis itaque accusantium quisquam. Delectus, eveniet ipsum!</p>
     </div>
    );
}
 
export default Help;